sudo: required

services:
  - docker

before_install:
  - docker build -t shanta280/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true shanta280/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-032161273886"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

